[package]
name = "smoothie"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2.5"
lyon = { version = "0.17.10", features = ["extra"] }
bytemuck = { version = "1.4", features = [ "derive" ] }